apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sindyffuse-preprocess-orchestrator
  labels:
    app: sindyffuse-preprocess-orchestrator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
